version: "3"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=3007
      - PGID=3007
      - TZ=Europe/Oslo
    volumes:
      - TNS_L_DATA:/data
      - TNS_L_CONF:/config
    ports:
      - 8020:443
    restart: always
    networks:
      - db_network
networks: 
  int_db:
    exrernal: true
volumes: 
  TNS_L_DATA:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.0.0.199,rw,nfsvers=4"
      device: ":/mnt/main/jarand/nextcloud"
  TNS_L_CONF:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.0.0.199,rw,nfsvers=4"
      device: ":/mnt/main/docker/nextcloud-conf"