version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.local.jarand.site'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://10.20.0.132'

        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "SMTP_SERVER"
        gitlab_rails['smtp_user_name'] = "SMTP_SERVER_USERNAME"
        gitlab_rails['smtp_password'] = "SMTP_SERVER_PASSWORD"
        gitlab_rails['smtp_domain'] = "DOMAIN"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['gitlab_email_from'] = 'FROM_EMAIL'
        gitlab_rails['gitlab_email_reply_to'] = 'REPLY_EMAIL'

        gitlab_rails['omniauth_enabled'] = true
        gitlab_rails['omniauth_allow_single_sign_on'] = ['saml']
        gitlab_rails['omniauth_sync_email_from_provider'] = 'saml'
        gitlab_rails['omniauth_sync_profile_from_provider'] = ['saml']
        gitlab_rails['omniauth_sync_profile_attributes'] = ['email']
        gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'saml'
        gitlab_rails['omniauth_block_auto_created_users'] = false
        gitlab_rails['omniauth_auto_link_saml_user'] = true
        gitlab_rails['omniauth_providers'] = [
          {
            name: "saml",
            label: "Provider name", # optional label for login button, defaults to "Saml"
            # ---- This tells GitLab OmniAuth which attribute has the groups ----
            groups_attribute: 'Groups',
            # ---- This tells which group to assign users admin permissions -----
            admin_groups: ['app-gitlab-admin'],
            args: {
              assertion_consumer_service_url: "",
              idp_cert_fingerprint: "",
              idp_sso_target_url: "",
              issuer: "",
              name_identifier_format: "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
              attribute_statements: {
                email: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'],
                first_name: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'],
                nickname: ['http://schemas.goauthentik.io/2021/02/saml/username']
                groups: ['http://schemas.xmlsoap.org/claims/Group']
              }
            },
            label: 'authentik'
          }
        ]
    ports:
      - '80:80'
      - '443:443'
      - '2424:22'
    volumes:
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - './data/data:/var/opt/gitlab'
    shm_size: '256m'