version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - nextcloud_config:/config
      - nextcloud_data:/data
    ports:
      - 8020:443
    restart: unless-stopped
    networks:
      - db_network
  # Database
  nextcloud-mysql: 
    image: mysql 
    restart: always  
    container_name: nextcloud-mysql 
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    networks:
      - db_network
networks: 
  db_network:
volumes: 
  db_data:
  nextcloud_data:
  nextcloud_config: