version: '3.3'

services:
  trilium: 
    image: zadam/trilium:latest
    restart: always  
    container_name: trilium-notes
    volumes:
      - TNS_L:/home/node/trilium-data
    ports:
      - '8060:8080'
    environment:
      USER_UID: "3005"
      USER_GID: "3005"
